template_path: src/rds.py

parameters:
  VpcId: !stack_output {{ env }}/vpc.yaml::VpcId
  Subnet1: !stack_output {{ env }}/vpc.yaml::PrivateSubnet1ID
  Subnet2: !stack_output {{ env }}/vpc.yaml::PrivateSubnet2ID
  Environment: !stack_output {{ env }}/vpc.yaml::Environment
  RDSSecurityGroup: !stack_output {{ env }}/security-groups.yaml::RDSsg
  MultiAZDatabase: "true"
  DBInstanceClass: db.t2.large
  DBAllocatedStorage: "7"
  DBName: wordpress
  DBPass: wordpress123
  DBUser: wordpress
  DatabaseEngine: MySQL

