template_path: src/efs.py

parameters:
  VpcId: !stack_output {{ env }}/vpc.yaml::VpcId
  Subnet1: !stack_output {{ env }}/vpc.yaml::PrivateSubnet1ID
  Subnet2: !stack_output {{ env }}/vpc.yaml::PrivateSubnet2ID
  Environment: !stack_output {{ env }}/vpc.yaml::Environment
  EfsSecurityGroup: !stack_output {{ env }}/security-groups.yaml::EFSsg
  PerformanceMode: generalPurpose
