template_path: src/wordpress.py

parameters:
  VpcId: !stack_output {{ env }}/vpc.yaml::VpcId
  Environment: !stack_output {{ env }}/vpc.yaml::Environment
  Subnet1: !stack_output {{ env }}/vpc.yaml::PublicSubnet1ID
  Subnet2: !stack_output {{ env }}/vpc.yaml::PublicSubnet2ID
  RDSEndpoint: !stack_output {{ env }}/rds.yaml::MySQLAddress
  FileSystemID: !stack_output {{ env }}/efs.yaml::FileSystemID
  ElbSecurityGroup: !stack_output {{ env }}/security-groups.yaml::ELBsg
  WebSecurityGroup: !stack_output {{ env }}/security-groups.yaml::WEBsg
  AvailabilityZone1: eu-west-1a
  AvailabilityZone2: eu-west-1b
  Hostname: www-dev
  Domain: meetup.celab.cloudreach.com
  KeyName: meetup.cloudreach
  InstanceType: t2.micro
  DBName: !stack_output {{ env }}/rds.yaml::DBName
  DBPass: wordpress123
  DBUser: !stack_output {{ env }}/rds.yaml::DBUser
  WebServerCapacity: "1"

